name: Build

on:
  push:
    branches: [main]
    tags: ['**']
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build
    if: ${{ !github.event.deleted }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Fetch Sources
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
        with:
          submodules: recursive
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961
        with:
          distribution: zulu
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb
        with:
          cache-provider: basic

      - name: Build plugin variants
        run: ./gradlew clean buildPluginVariants --no-daemon

      - name: Upload plugin variants
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: plugin-variants
          path: build/distributions/*.zip
          if-no-files-found: error
          compression-level: 0
          retention-days: 90
          overwrite: true

  release:
    name: Draft release
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/') && !github.event.deleted }}
    permissions:
      actions: read
      contents: write
    uses: ./.github/workflows/release.yml
